services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AMULEX_BUILD_CORPUS_PORT:-8501}:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run script/app.py
